services:
  - type: web
    name: identity-reconciliation
    runtime: node
    plan: free
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: postgresql://bitspeed_shantanu_user:VxqMOCMlqLQgAGDLXkC3ZuJQeXXy9WWg@dpg-d6gs9evgi27c73ffrmk0-a/bitspeed_shantanu
